image: node:10.5.0

stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: production
    url: https://elated-mclean-3f8e20.netlify.com/
  only:
    - master
  script:
    - npm i -g
    # your build command
    #- npm run build
    - npm install ngx -g
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod