image: node:10.5.0

stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: production
    url: https://your.website.com
  script:
    - npm install
    # your build command
    #- npm run build
    - npm install -g npx
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod