image: node:10.5.0

stages:
  - build
  - test
  - deploy

before_script:
  - npm install

job:1:
  stage: build
  script: echo 'my first job'

job:2:
  stage: test
  script: 
    - echo 'my second job'
    - npm build